title: "Theo Queval"
email: "theoqueval@yahoo.com"
description: "Portfolio de Theo Queval - Développeur & Créateur de projets hardware."

# Pour les images
url: "https://theoqueval.github.io"
baseurl: ""

# CONFIGURATION JEKYLL
markdown: kramdown
highlighter: rouge
include: ["_pages", ".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/"]

collections:
  posts:
    output: true
    permalink: /projets/:title/

author:
  name   : "Theo Queval"
  avatar : "/assets/images/photo-profil.jpg"
  bio    : "Développeur Fullstack | Passionné par l'embarqué et l'électronique"
  location: "Lens, France"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ton-pseudo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ton-pseudo"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed